[core_settings]
# The CI already timestamps the logs
log_timestamp = false
log_error_details = true

# The container runs the Parsec service as root, so make sure we disable root
# checks.
allow_root = true

[listener]
listener_type = "DomainSocket"
# The timeout needs to be smaller than the test client timeout (five seconds) as it is testing
# that the service does not hang for very big values of body or authentication length.
timeout = 3000 # in milliseconds
socket_path = "/tmp/parsec.sock"

[authenticator]
#auth_type = "Direct"
auth_type = "UnixPeerCredentials"

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"
store_path = "./mappings"

[[provider]]
provider_type = "Pkcs11"
key_info_manager = "on-disk-manager"
#library_path = "/usr/local/lib/softhsm/libsofthsm2.so"
library_path = "/usr/lib/libckteec.so"
user_pin = "123456"
software_public_operations = false
# The slot_number mandatory field is going to replace the following line with a valid number
# slot_number
slot_number = 0
